/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pending;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import config.KoneksiDatabase;

import javax.swing.table.DefaultTableModel;


public class FormApproval extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormApproval
     */
    DefaultTableModel modelReview;

    public FormApproval() {
        initComponents();

        siapkanTabel();
        loadNimPending();
    }

    private void siapkanTabel() {
        modelReview = new DefaultTableModel();
        modelReview.addColumn("Kode MK");
        modelReview.addColumn("Nama Mata Kuliah");
        modelReview.addColumn("SKS");
        modelReview.addColumn("Status");
        table_review.setModel(modelReview);
    }

    private void loadNimPending() {
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
         
            String sql = "SELECT DISTINCT nim FROM krs WHERE status_dospen = 'pending' OR status_kaprodi = 'pending'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cb_nimpending.removeAllItems();
            cb_nimpending.addItem("-- Pilih Mahasiswa --");

            while (rs.next()) {
                cb_nimpending.addItem(rs.getString("nim"));
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error load NIM Pending: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cb_nimpending = new javax.swing.JComboBox<>();
        tf_kolomnama = new javax.swing.JTextField();
        tf_kolomsemester = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_review = new javax.swing.JTable();
        btn_acc = new javax.swing.JButton();
        btn_tolakkrs = new javax.swing.JButton();
        tf_kolomtotalSks = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Approval");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        cb_nimpending.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_nimpending.addActionListener(this::cb_nimpendingActionPerformed);

        tf_kolomnama.setEditable(false);
        tf_kolomnama.setText("Nama");

        tf_kolomsemester.setEditable(false);
        tf_kolomsemester.setText("Semester");

        table_review.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_review);

        btn_acc.setText("ACC");
        btn_acc.addActionListener(this::btn_accActionPerformed);

        btn_tolakkrs.setText("Tolak KRS");
        btn_tolakkrs.addActionListener(this::btn_tolakkrsActionPerformed);

        tf_kolomtotalSks.setEditable(false);
        tf_kolomtotalSks.setText("Total SKS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_nimpending, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_kolomnama, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_tolakkrs, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_kolomtotalSks, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_kolomsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nimpending, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kolomnama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kolomsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tolakkrs, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kolomtotalSks, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_nimpendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nimpendingActionPerformed
        // TODO add your handling code here:
        if (cb_nimpending.getSelectedIndex() > 0) {
            try {
                Connection conn = KoneksiDatabase.dB_koneksi();
                String nim = cb_nimpending.getSelectedItem().toString();

                String sqlMhs = "SELECT nama, semester_aktif FROM mahasiswa WHERE nim = ?";
                PreparedStatement pstMhs = conn.prepareStatement(sqlMhs);
                pstMhs.setString(1, nim);
                ResultSet rsMhs = pstMhs.executeQuery();
                if (rsMhs.next()) {
                    tf_kolomnama.setText(rsMhs.getString("nama"));
                    tf_kolomsemester.setText(rsMhs.getString("semester_aktif"));
                }
                rsMhs.close();
                pstMhs.close();

                modelReview.setRowCount(0);
                int totalSks = 0;

                String sqlKrs = "SELECT k.kode_mk, m.nama_mk, m.sks, k.status_dospen, k.status_kaprodi FROM krs k JOIN mata_kuliah m ON k.kode_mk = m.kode_mk WHERE k.nim = ? AND (k.status_dospen = 'pending' OR k.status_kaprodi = 'pending')";
                PreparedStatement pstKrs = conn.prepareStatement(sqlKrs);
                pstKrs.setString(1, nim);
                ResultSet rsKrs = pstKrs.executeQuery();

                while (rsKrs.next()) {
                    String kode = rsKrs.getString("kode_mk");
                    String namaMk = rsKrs.getString("nama_mk");
                    int sks = rsKrs.getInt("sks");

                    String statusTampil = "Dospen: " + rsKrs.getString("status_dospen") + " | Kaprodi: " + rsKrs.getString("status_kaprodi");

                    modelReview.addRow(new Object[]{kode, namaMk, sks, statusTampil});
                    totalSks += sks;
                }
                rsKrs.close();
                pstKrs.close();

                tf_kolomtotalSks.setText(String.valueOf(totalSks) + " SKS");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error load data review: " + e.getMessage());
            }
        } else {

            tf_kolomnama.setText("");
            tf_kolomsemester.setText("");
            tf_kolomsemester.setText("");
            if (modelReview != null) {
                modelReview.setRowCount(0);
            }
        }
    }//GEN-LAST:event_cb_nimpendingActionPerformed

    private void btn_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accActionPerformed
        // TODO add your handling code here:

        if (cb_nimpending.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Silakan pilih mahasiswa terlebih dahulu!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menyetujui (" + tf_kolomtotalSks.getText() + ") KRS mahasiswa ini?", "Konfirmasi ACC", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = KoneksiDatabase.dB_koneksi();
                String nim = cb_nimpending.getSelectedItem().toString();

     
                String sql = "UPDATE krs SET status_dospen = 'ACC', status_kaprodi = 'ACC' WHERE nim = ? AND (status_dospen = 'pending' OR status_kaprodi = 'pending')";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, nim);
                pst.execute();

                JOptionPane.showMessageDialog(this, "KRS Berhasil Di-ACC Sepenuhnya!");

                loadNimPending(); 
                tf_kolomnama.setText("");
                tf_kolomsemester.setText("");
                tf_kolomtotalSks.setText("");
                modelReview.setRowCount(0);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal ACC KRS: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btn_accActionPerformed

    private void btn_tolakkrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tolakkrsActionPerformed
        // TODO add your handling code here:

        if (cb_nimpending.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Silakan pilih mahasiswa terlebih dahulu!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Tolak dan kembalikan KRS mahasiswa ini?", "Konfirmasi Tolak", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = KoneksiDatabase.dB_koneksi();
                String nim = cb_nimpending.getSelectedItem().toString();

                String sql = "DELETE FROM krs WHERE nim = ? AND (status_dospen = 'pending' OR status_kaprodi = 'pending')";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, nim);
                pst.execute();

                JOptionPane.showMessageDialog(this, "KRS Ditolak. Mahasiswa harus menginput ulang.");

                loadNimPending();
                tf_kolomnama.setText("");
                tf_kolomsemester.setText("");
                tf_kolomtotalSks.setText("");
                modelReview.setRowCount(0);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menolak KRS: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_tolakkrsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acc;
    private javax.swing.JButton btn_tolakkrs;
    private javax.swing.JComboBox<String> cb_nimpending;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_review;
    private javax.swing.JTextField tf_kolomnama;
    private javax.swing.JTextField tf_kolomsemester;
    private javax.swing.JTextField tf_kolomtotalSks;
    // End of variables declaration//GEN-END:variables
}
