package views;

import config.KoneksiDatabase;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

public class FormMahasiswa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa() {
        initComponents();
        tampilData();
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIM");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("NIP Dospem");
        model.addColumn("Semester");

        table_daftarMahasiswa.setModel(model);

        try {

            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();

            String sql = "SELECT * FROM mahasiswa";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nim"),
                    rs.getString("nama"),
                    rs.getString("alamat"),
                    rs.getString("nip_dospem"),
                    rs.getString("semester_aktif")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tf_kolomnim = new javax.swing.JTextField();
        tf_kolomnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_alamat = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        tf_kolomnipDospem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_daftarMahasiswa = new javax.swing.JTable();
        tf_kolomsemester = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Daftar Mahasiswa");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        tf_kolomnim.setText("NIM");

        tf_kolomnama.setText("Nama");

        ta_alamat.setColumns(20);
        ta_alamat.setRows(5);
        ta_alamat.setText("Alamat...");
        jScrollPane1.setViewportView(ta_alamat);

        btn_save.setText("Save");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        tf_kolomnipDospem.setText("NIM Dosen Pembimbing");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Mahasiswa");

        table_daftarMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_daftarMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_daftarMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_daftarMahasiswa);

        tf_kolomsemester.setText("semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_kolomnama, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_kolomnipDospem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_kolomnim, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_kolomsemester, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_kolomnim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_kolomnama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_kolomsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_kolomnipDospem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:

        try {

            String sql = "INSERT INTO mahasiswa (nim, nama, alamat, nip_dospem, semester_aktif) VALUES (?, ?, ?, ?, ?)";
            Connection conn = KoneksiDatabase.dB_koneksi();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tf_kolomnim.getText());
            pst.setString(2, tf_kolomnama.getText());
            pst.setString(3, ta_alamat.getText());
            pst.setString(4, tf_kolomnipDospem.getText());
            pst.setInt(5, Integer.parseInt(tf_kolomsemester.getText()));

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Mahasiswa Berhasil Disimpan!");

            tampilData();

            tf_kolomnim.setText("");
            tf_kolomnama.setText("");
            ta_alamat.setText("");
            tf_kolomnipDospem.setText("");
            tf_kolomsemester.setText("");
            tf_kolomnim.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data: " + e.getMessage());
            System.err.println("Error" + e.getMessage());
        }


    }//GEN-LAST:event_btn_saveActionPerformed

    private void table_daftarMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_daftarMahasiswaMouseClicked
        // TODO add your handling code here:
        int baris = table_daftarMahasiswa.getSelectedRow();

        if (baris != -1) {
            // Mengambil data dari tabel (ingat, index kolom dimulai dari 0)
            tf_kolomnim.setText(table_daftarMahasiswa.getValueAt(baris, 0).toString());
            tf_kolomnama.setText(table_daftarMahasiswa.getValueAt(baris, 1).toString());
            ta_alamat.setText(table_daftarMahasiswa.getValueAt(baris, 2).toString());
            tf_kolomnipDospem.setText(table_daftarMahasiswa.getValueAt(baris, 3).toString());
            tf_kolomsemester.setText(table_daftarMahasiswa.getValueAt(baris, 4).toString());

            tf_kolomnim.setEditable(false);
        }
    }//GEN-LAST:event_table_daftarMahasiswaMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:

        try {

            String sql = "UPDATE mahasiswa SET nama=?, alamat=?, nip_dospem=?, semester_aktif=? WHERE nim=?";
            Connection conn = KoneksiDatabase.dB_koneksi();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tf_kolomnama.getText());
            pst.setString(2, ta_alamat.getText());
            pst.setString(3, tf_kolomnipDospem.getText());
            pst.setInt(4, Integer.parseInt(tf_kolomsemester.getText()));
            pst.setString(5, tf_kolomnim.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Mahasiswa Berhasil Diubah!");

            tampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Mengubah Data: " + e.getMessage());
            System.err.println("Error:" + e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM mahasiswa WHERE nim=?";
                Connection conn = KoneksiDatabase.dB_koneksi();
                PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, tf_kolomnim.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
                tampilData();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus Data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:

        tf_kolomnim.setText("");
        tf_kolomnama.setText("");
        ta_alamat.setText("");
        tf_kolomnipDospem.setText("");

        tf_kolomnim.setEditable(true);

        tf_kolomnim.requestFocus();
    }//GEN-LAST:event_btn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ta_alamat;
    private javax.swing.JTable table_daftarMahasiswa;
    private javax.swing.JTextField tf_kolomnama;
    private javax.swing.JTextField tf_kolomnim;
    private javax.swing.JTextField tf_kolomnipDospem;
    private javax.swing.JTextField tf_kolomsemester;
    // End of variables declaration//GEN-END:variables
}
