/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import config.KoneksiDatabase;

public class FormMatkul extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormMatkul
     */
    public FormMatkul() {
        initComponents();

        tampilData();
        loadDosen();
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode MK");
        model.addColumn("Nama Mata Kuliah");
        model.addColumn("SKS");
        model.addColumn("Semester");
        model.addColumn("NIP Pengajar");

        table_matkul.setModel(model);

        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM mata_kuliah");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_mk"),
                    rs.getString("nama_mk"),
                    rs.getString("sks"),
                    rs.getString("semester"),
                    rs.getString("nip_pengajar")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data Matkul: " + e.getMessage());
        }
    }

    private void loadDosen() {
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nip, nama FROM dosen");

            cb_nipPengajar.removeAllItems();
            cb_nipPengajar.addItem("-- Pilih Dosen Pengajar --");

            while (rs.next()) {

                cb_nipPengajar.addItem(rs.getString("nip") + " - " + rs.getString("nama"));
            }
        } catch (Exception e) {
            System.err.println("Gagal load dosen: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tf_kolomkodeMatkul = new javax.swing.JTextField();
        tf_kolommataKuliah = new javax.swing.JTextField();
        cb_sks = new javax.swing.JComboBox<>();
        cb_semester = new javax.swing.JComboBox<>();
        cb_nipPengajar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_matkul = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Mata Kuliah");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        tf_kolomkodeMatkul.setText("Kode mata kuliah");

        tf_kolommataKuliah.setText("Mata kuliah");

        cb_sks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih SKS ---", "2", "3" }));

        cb_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Semester --", "1", "2", "3", "4", "5", "6", "7", "8" }));

        cb_nipPengajar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        table_matkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_matkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_matkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_matkul);

        btn_add.setText("Add");
        btn_add.addActionListener(this::btn_addActionPerformed);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_kolommataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tf_kolomkodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(cb_sks, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(cb_nipPengajar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_kolomkodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_sks, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_nipPengajar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_kolommataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_matkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_matkulMouseClicked
        int baris = table_matkul.getSelectedRow();
        if (baris != -1) {

            String kodeMk = table_matkul.getValueAt(baris, 0) != null ? table_matkul.getValueAt(baris, 0).toString() : "";
            String namaMk = table_matkul.getValueAt(baris, 1) != null ? table_matkul.getValueAt(baris, 1).toString() : "";
            String sks = table_matkul.getValueAt(baris, 2) != null ? table_matkul.getValueAt(baris, 2).toString() : "";
            String semester = table_matkul.getValueAt(baris, 3) != null ? table_matkul.getValueAt(baris, 3).toString() : "";
            String nip = table_matkul.getValueAt(baris, 4) != null ? table_matkul.getValueAt(baris, 4).toString() : "";

            tf_kolomkodeMatkul.setText(kodeMk);
            tf_kolommataKuliah.setText(namaMk);

            if (!sks.isEmpty()) {
                cb_sks.setSelectedItem(sks);
            } else {
                cb_sks.setSelectedIndex(0); 
            }
            if (!semester.isEmpty()) {
                cb_semester.setSelectedItem(semester);
            } else {
                cb_semester.setSelectedIndex(0);
            }

            if (nip == null || nip.isEmpty()) {
                cb_nipPengajar.setSelectedIndex(0);
            } else {
                boolean ditemukan = false;
                for (int i = 0; i < cb_nipPengajar.getItemCount(); i++) {
                    if (cb_nipPengajar.getItemAt(i).toString().startsWith(nip)) {
                        cb_nipPengajar.setSelectedIndex(i);
                        ditemukan = true;
                        break;
                    }
                }
                if (!ditemukan) {
                    cb_nipPengajar.setSelectedIndex(0);
                }
            }

            tf_kolomkodeMatkul.setEditable(false);
        }
    }//GEN-LAST:event_table_matkulMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (tf_kolomkodeMatkul.getText().isEmpty() || tf_kolommataKuliah.getText().isEmpty() || cb_sks.getSelectedIndex() == 0 || cb_semester.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Kode, Nama Matkul, SKS, dan Semester wajib diisi!");
            return;
        }

        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            String sql = "INSERT INTO mata_kuliah (kode_mk, nama_mk, sks, semester, nip_pengajar) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tf_kolomkodeMatkul.getText());
            pst.setString(2, tf_kolommataKuliah.getText());
            pst.setString(3, cb_sks.getSelectedItem().toString());
            pst.setString(4, cb_semester.getSelectedItem().toString());

            
            if (cb_nipPengajar.getSelectedIndex() == 0) {
                pst.setNull(5, java.sql.Types.VARCHAR);
            } else {
                String nipPengajar = cb_nipPengajar.getSelectedItem().toString().split(" - ")[0];
                pst.setString(5, nipPengajar);
            }

            pst.execute();
            JOptionPane.showMessageDialog(this, "Mantap! Data Mata Kuliah Berhasil Ditambahkan!");

            tampilData();
            btn_clearActionPerformed(evt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            String sql = "UPDATE mata_kuliah SET nama_mk=?, sks=?, semester=?, nip_pengajar=? WHERE kode_mk=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tf_kolommataKuliah.getText());
            pst.setString(2, cb_sks.getSelectedItem().toString());
            pst.setString(3, cb_semester.getSelectedItem().toString());

            if (cb_nipPengajar.getSelectedIndex() == 0) {
                pst.setNull(4, java.sql.Types.VARCHAR);
            } else {
                String nipPengajar = cb_nipPengajar.getSelectedItem().toString().split(" - ")[0];
                pst.setString(4, nipPengajar);
            }

            pst.setString(5, tf_kolomkodeMatkul.getText());

            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");
            tampilData();
            btn_clearActionPerformed(evt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Edit: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (tf_kolomkodeMatkul.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dihapus!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus Mata Kuliah ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = KoneksiDatabase.dB_koneksi();
                String sql = "DELETE FROM mata_kuliah WHERE kode_mk=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, tf_kolomkodeMatkul.getText());

                pst.execute();
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");

                tampilData();
                btn_clearActionPerformed(evt);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus Data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        tf_kolomkodeMatkul.setText("");
        tf_kolommataKuliah.setText("");

        if (cb_sks.getItemCount() > 0) {
            cb_sks.setSelectedIndex(0);
        }
        if (cb_semester.getItemCount() > 0) {
            cb_semester.setSelectedIndex(0);
        }
        if (cb_nipPengajar.getItemCount() > 0) {
            cb_nipPengajar.setSelectedIndex(0);
        }

        tf_kolomkodeMatkul.setEditable(true);
        tf_kolomkodeMatkul.requestFocus();

    }//GEN-LAST:event_btn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JComboBox<String> cb_nipPengajar;
    private javax.swing.JComboBox<String> cb_semester;
    private javax.swing.JComboBox<String> cb_sks;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_matkul;
    private javax.swing.JTextField tf_kolomkodeMatkul;
    private javax.swing.JTextField tf_kolommataKuliah;
    // End of variables declaration//GEN-END:variables
}
