/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import config.KoneksiDatabase;
import javax.swing.JOptionPane;

public class FormAddUsers extends javax.swing.JInternalFrame {

    String idUserTerpilih = "";

    /**
     * Creates new form FormAkun
     */
    public FormAddUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tf_kolomnama = new javax.swing.JTextField();
        tf_kolomuser = new javax.swing.JTextField();
        pf_kolompass = new javax.swing.JPasswordField();
        cbb_role = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Users");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        tf_kolomnama.setText("Nama lengkap...");
        tf_kolomnama.addActionListener(this::tf_kolomnamaActionPerformed);

        tf_kolomuser.setText("Username...");

        pf_kolompass.setText("password...");

        cbb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Role ---", "operator" }));
        cbb_role.addActionListener(this::cbb_roleActionPerformed);

        btn_save.setText("Save");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        jLabel1.setText("Role");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tambahkan data user baru ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(tf_kolomnama)
                        .addComponent(tf_kolomuser)
                        .addComponent(pf_kolompass, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cbb_role, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(tf_kolomnama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_kolomuser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_kolompass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String namaLengkap = tf_kolomnama.getText();
        String username = tf_kolomuser.getText();
        String password = String.valueOf(pf_kolompass.getPassword());

        if (namaLengkap.isEmpty() || username.isEmpty() || password.isEmpty() || cbb_role.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data (Nama, Username, Password, dan Role)!");
            return; 
        }

        try {

            Connection conn = KoneksiDatabase.dB_koneksi();
            String sql = "INSERT INTO user (nama_lengkap, username, password, role) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, namaLengkap);
            pst.setString(2, username);
            pst.setString(3, password);
            pst.setString(4, cbb_role.getSelectedItem().toString());

            pst.execute();
            JOptionPane.showMessageDialog(this, "User berhasil ditambahkan!");

            btn_clearActionPerformed(evt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan user: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        tf_kolomnama.setText("");
        tf_kolomuser.setText("");
        pf_kolompass.setText("");
        cbb_role.setSelectedIndex(0);

        tf_kolomnama.requestFocus();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void cbb_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_roleActionPerformed

    private void tf_kolomnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kolomnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kolomnamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbb_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pf_kolompass;
    private javax.swing.JTextField tf_kolomnama;
    private javax.swing.JTextField tf_kolomuser;
    // End of variables declaration//GEN-END:variables
}
