package views;

import config.KoneksiDatabase;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormKRS extends javax.swing.JInternalFrame {

    int totalSksSaatIni = 0;
    int batasSks = 21;
    DefaultTableModel modelDraft;

    /**
     * Creates new form FormKRS
     */
    public FormKRS() {
        initComponents();

//        tampilMataKuliah();
        modelDraft = new DefaultTableModel();
        modelDraft.addColumn("Kode MK");
        modelDraft.addColumn("Nama MK");
        modelDraft.addColumn("SKS");
        table_daftar.setModel(modelDraft);

        tampilNim();
    }

    private void tampilNim() {
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nim FROM mahasiswa");

            cb_nim.removeAllItems();
            cb_nim.addItem("-- Pilih NIM --");

            while (rs.next()) {
                cb_nim.addItem(rs.getString("nim"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Load NIM: " + e.getMessage());
        }
    }

    private void tampilMataKuliah(int semesterAktif) {
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();

            String sql = "";
            if (semesterAktif % 2 == 0) {

                sql = "SELECT kode_mk, nama_mk FROM mata_kuliah WHERE semester % 2 = 0";
            } else {
                sql = "SELECT kode_mk, nama_mk FROM mata_kuliah WHERE semester % 2 != 0";
            }

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cb_matkul.removeAllItems();
            cb_matkul.addItem("-- Pilih Mata Kuliah --");

            while (rs.next()) {
                cb_matkul.addItem(rs.getString("kode_mk") + " - " + rs.getString("nama_mk"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Load Matkul: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cb_nim = new javax.swing.JComboBox<>();
        tf_kolomnama = new javax.swing.JTextField();
        tf_kolomsemester = new javax.swing.JTextField();
        btn_tambahdraft = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_matkul = new javax.swing.JComboBox<>();
        tf_kolomsks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_daftar = new javax.swing.JTable();
        btn_simpanKRS = new javax.swing.JButton();
        tf_infoBatas = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form KRS");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        cb_nim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "Item 2", "Item 3", "Item 4" }));
        cb_nim.addActionListener(this::cb_nimActionPerformed);

        tf_kolomnama.setEditable(false);
        tf_kolomnama.setText("Nama Mahasiswa");

        tf_kolomsemester.setEditable(false);
        tf_kolomsemester.setText("Semester Tempuh");
        tf_kolomsemester.addActionListener(this::tf_kolomsemesterActionPerformed);
        tf_kolomsemester.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_kolomsemesterKeyReleased(evt);
            }
        });

        btn_tambahdraft.setText("Tambahkan ke Draft");
        btn_tambahdraft.addActionListener(this::btn_tambahdraftActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Identitas Mahasiswa");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Pemilihan Mata Kuliah");

        cb_matkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MataKuliah", "Item 2", "Item 3", "Item 4" }));
        cb_matkul.addActionListener(this::cb_matkulActionPerformed);

        tf_kolomsks.setEditable(false);
        tf_kolomsks.setText("SKS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Daftar Pilihan");

        table_daftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_daftarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_daftar);

        btn_simpanKRS.setText("Simpan KRS");
        btn_simpanKRS.addActionListener(this::btn_simpanKRSActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_kolomnama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_nim, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_kolomsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_kolomsks, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_tambahdraft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_infoBatas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpanKRS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cb_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_kolomnama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_kolomsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_kolomsks, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_tambahdraft, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_infoBatas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_simpanKRS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nimActionPerformed
        // TODO add your handling code here:

        if (cb_nim.getSelectedIndex() > 0) {
            try {
                String nimDipilih = cb_nim.getSelectedItem().toString();
                Connection conn = KoneksiDatabase.dB_koneksi();

                String sqlMhs = "SELECT nama, semester_aktif FROM mahasiswa WHERE nim = ?";
                PreparedStatement pstMhs = conn.prepareStatement(sqlMhs);
                pstMhs.setString(1, nimDipilih);
                ResultSet rsMhs = pstMhs.executeQuery();

                int smtAktif = 1;
                if (rsMhs.next()) {
                    tf_kolomnama.setText(rsMhs.getString("nama"));
                    smtAktif = rsMhs.getInt("semester_aktif");
                    tf_kolomsemester.setText(String.valueOf(smtAktif)); 

                    tampilMataKuliah(smtAktif);
                }

                String sqlIP = "SELECT AVG(nilai_angka) as ipk FROM nilai WHERE nim = ?";
                PreparedStatement pstIP = conn.prepareStatement(sqlIP);
                pstIP.setString(1, nimDipilih);
                ResultSet rsIP = pstIP.executeQuery();

                int batasMatkul = 7; 
                batasSks = 21; 

                if (rsIP.next() && rsIP.getString("ipk") != null) {
                    double ipk = rsIP.getDouble("ipk");
                    if (ipk > 3.5) {
                        batasSks = 24;
                        batasMatkul = 8; 
                    }
                }

                modelDraft.setRowCount(0); 
                totalSksSaatIni = 0;

                String sqlPaket = "SELECT kode_mk, nama_mk, sks FROM mata_kuliah WHERE semester = ?";
                PreparedStatement pstPaket = conn.prepareStatement(sqlPaket);
                pstPaket.setInt(1, smtAktif);
                ResultSet rsPaket = pstPaket.executeQuery();

                while (rsPaket.next()) {
                    String kode = rsPaket.getString("kode_mk");
                    String nama = rsPaket.getString("nama_mk");
                    int sks = rsPaket.getInt("sks");

                    modelDraft.addRow(new Object[]{kode, nama, sks});
                    totalSksSaatIni += sks;
                }

                int matkulSaatIni = modelDraft.getRowCount();
                tf_infoBatas.setText("SKS: " + totalSksSaatIni + "/" + batasSks + " | Matkul: " + matkulSaatIni + "/" + batasMatkul);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error load data mahasiswa: " + e.getMessage());
            }
        } else {
          
            tf_kolomnama.setText("");
            tf_kolomsemester.setText("");
            modelDraft.setRowCount(0);
            totalSksSaatIni = 0;
            tf_infoBatas.setText("");
            cb_matkul.removeAllItems();
        }
    }//GEN-LAST:event_cb_nimActionPerformed

    private void cb_matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_matkulActionPerformed
        // TODO add your handling code here:

        if (cb_matkul.getSelectedIndex() > 0) {
            try {

                String itemDipilih = cb_matkul.getSelectedItem().toString();
                String kodeMk = itemDipilih.split(" - ")[0];

                Connection conn = KoneksiDatabase.dB_koneksi();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery("SELECT sks FROM mata_kuliah WHERE kode_mk='" + kodeMk + "'"); // SQL INJECT

                if (rs.next()) {
                    tf_kolomsks.setText(rs.getString("sks"));
                }
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        } else {
            tf_kolomsks.setText("");
        }
    }//GEN-LAST:event_cb_matkulActionPerformed

    private void btn_simpanKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanKRSActionPerformed
        // TODO add your handling code here:

        if (modelDraft.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Keranjang KRS masih kosong!");
            return;
        }

        if (tf_kolomsemester.getText().isEmpty() || cb_nim.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Pastikan NIM dan Semester Tempuh sudah diisi!");
            return;
        }

        try {
            Connection conn = KoneksiDatabase.dB_koneksi();

            String sql = "INSERT INTO krs (nim, kode_mk, semester_tempuh) VALUES (?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            String nim = cb_nim.getSelectedItem().toString();
            int semester = Integer.parseInt(tf_kolomsemester.getText());

            for (int i = 0; i < modelDraft.getRowCount(); i++) {
                String kodeMk = modelDraft.getValueAt(i, 0).toString();

                pst.setString(1, nim);
                pst.setString(2, kodeMk);
                pst.setInt(3, semester);

                pst.addBatch();
            }

            pst.executeBatch();
            JOptionPane.showMessageDialog(this, "KRS Berhasil Diajukan! Menunggu ACC Dosen.");

            modelDraft.setRowCount(0);
            totalSksSaatIni = 0;
            cb_matkul.setSelectedIndex(0);

            tf_infoBatas.setText("Total SKS: 0 / Maksimal: " + batasSks + " SKS");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan KRS: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanKRSActionPerformed

    private void btn_tambahdraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahdraftActionPerformed
        // TODO add your handling code here:
        if (cb_matkul.getSelectedIndex() > 0 && !tf_kolomsks.getText().isEmpty()) {
            String itemDipilih = cb_matkul.getSelectedItem().toString();
            String kodeMk = itemDipilih.split(" - ")[0];
            String namaMk = itemDipilih.split(" - ")[1];
            int sksDipilih = Integer.parseInt(tf_kolomsks.getText());

            int batasMatkul = (batasSks == 24) ? 8 : 7;
            int matkulSaatIni = modelDraft.getRowCount();

            if (matkulSaatIni >= batasMatkul) {
                JOptionPane.showMessageDialog(this, "Maksimal matkul tercapai! (Batas: " + batasMatkul + " Mata Kuliah)");
                return;
            }

            if ((totalSksSaatIni + sksDipilih) > batasSks) {
                JOptionPane.showMessageDialog(this, "Total SKS melebihi batas maksimal (" + batasSks + " SKS)!");
                return;
            }

            for (int i = 0; i < matkulSaatIni; i++) {
                if (modelDraft.getValueAt(i, 0).toString().equals(kodeMk)) {
                    JOptionPane.showMessageDialog(this, "Mata kuliah ini sudah ada di daftar!");
                    return;
                }
            }

            modelDraft.addRow(new Object[]{kodeMk, namaMk, sksDipilih});
            totalSksSaatIni += sksDipilih;

            // Update TextField Info Batas
            tf_infoBatas.setText("SKS: " + totalSksSaatIni + "/" + batasSks + " | Matkul: " + modelDraft.getRowCount() + "/" + batasMatkul);

        } else {
            JOptionPane.showMessageDialog(this, "Pilih mata kuliah terlebih dahulu!");
        }
    }//GEN-LAST:event_btn_tambahdraftActionPerformed

    private void tf_kolomsemesterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_kolomsemesterKeyReleased
        // TODO add your handling code here:
        try {

            if (!tf_kolomsemester.getText().isEmpty()) {
                int smt = Integer.parseInt(tf_kolomsemester.getText());
                tampilMataKuliah(smt);
            } else {

                cb_matkul.removeAllItems();
                cb_matkul.addItem("-- Pilih Mata Kuliah --");
            }

        } catch (NumberFormatException e) {
            System.err.println("Err: " + e.getMessage());
        }
    }//GEN-LAST:event_tf_kolomsemesterKeyReleased

    private void tf_kolomsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kolomsemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kolomsemesterActionPerformed

    private void table_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_daftarMouseClicked
        // TODO add your handling code here:
        int baris = table_daftar.getSelectedRow();

        if (baris != -1) {
            String namaMk = modelDraft.getValueAt(baris, 1).toString();

            int konfirmasi = JOptionPane.showConfirmDialog(this,
                    "Hapus mata kuliah [" + namaMk + "] dari draft?",
                    "Konfirmasi Hapus Draft", JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                int sksDihapus = Integer.parseInt(modelDraft.getValueAt(baris, 2).toString());

                totalSksSaatIni -= sksDihapus;

                modelDraft.removeRow(baris);

                int batasMatkul = (batasSks == 24) ? 8 : 7;
                tf_infoBatas.setText("SKS: " + totalSksSaatIni + "/" + batasSks + " | Matkul: " + modelDraft.getRowCount() + "/" + batasMatkul);
//                tf_infoBatas.setText("Total SKS: " + totalSksSaatIni + " / Maksimal: " + batasSks + " SKS");

                JOptionPane.showMessageDialog(this, "Mata kuliah berhasil dikeluarkan dari draft.");
            }
        }
    }//GEN-LAST:event_table_daftarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpanKRS;
    private javax.swing.JButton btn_tambahdraft;
    private javax.swing.JComboBox<String> cb_matkul;
    private javax.swing.JComboBox<String> cb_nim;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_daftar;
    private javax.swing.JTextField tf_infoBatas;
    private javax.swing.JTextField tf_kolomnama;
    private javax.swing.JTextField tf_kolomsemester;
    private javax.swing.JTextField tf_kolomsks;
    // End of variables declaration//GEN-END:variables
}
